apiVersion: v1
kind: ServiceAccount
metadata:
  name: nectar

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nectar
subjects:
- kind: User
  name: system:serviceaccount:default:nectar
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io