steps:

  - id: "Build Virtual Cluster"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "build"
      - "."
      - "-f"
      - "CreateKindDockerfile"
      - "-t"
      - "test-suite-cluster:latest"
      - "--cache-from"
      - "ubuntu"

  - id: "Build Test Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "build"
      - "."
      - "--cache-from"
      - "gcr.io/nectar-bazaar/test-run:latest"
      - "-f"
      - "TestImageDockerfile"
      - "-t"
      - "test-run:latest"

  - id: "Cache Test Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Build Test Image"]
    args:
      - "push"
      - "gcr.io/nectar-bazaar/test-run:latest"

  - id: "Run Tests in Virtual Cluster"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Build Virtual Cluster", "Build Test Image"]
    args:
      - "run"
      - "-v"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "--net=host"
      - "test-suite-cluster:latest"

  - id: "Publish"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Run Tests in Virtual Cluster"]
    args:
      - 'run'
      - 'test-run:latest'
      - 'pipenv'
      - 'run'
      - "python3"
      - "-m"
      - "twine"
      - "upload"
      - "-u"
      - "xnectar"
      - "-p"
      - "${_PASSWORD}"
      - "/app/dist/*;"
      - "exit"
      - "0"