images:
  - "gcr.io/nectar-bazaar/k8-kat:latest"

steps:

  - id: "Build Virtual Cluster"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "build"
      - "."
      - "-f"
      - "CreateKindDockerfile"
      - "-t"
      - "test-suite-cluster:latest"
      - "--cache-from"
      - "gcr.io/nectar-bazaar/kind-base:latest"

  - id: "Pull Cached Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "pull"
      - "gcr.io/nectar-bazaar/k8-kat:latest"

  - id: "Build Test Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Pull Cached Image"]
    args:
      - "build"
      - "."
      - "--cache-from"
      - "gcr.io/nectar-bazaar/k8-kat:latest"
      - "--build-arg"
      - "CODECOV_TOKEN=${_CODECOV_TOKEN}"
      - "-t"
      - "k8-kat:latest"
      - "-t"
      - "gcr.io/nectar-bazaar/k8-kat:latest"

  - id: "Run Tests in Virtual Cluster"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Build Virtual Cluster", "Build Test Image"]
    args:
      - "run"
      - "-v"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "--net=host"
      - "test-suite-cluster:latest"

  - id: "Publish"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Run Tests in Virtual Cluster"]
    args:
      - 'run'
      - "--env"
      - "PASSWORD=${_PASSWORD}"
      - 'k8-kat:latest'
      - "publish"