apiVersion: batch/v1
kind: Job
metadata:
  namespace: nectar
  name: docker-test

spec:
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      namespace: nectar
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: docker:latest
          command: ["docker",  "image", "ls"]
          env:
            - name: DOCKER_HOST
              value: tcp://10.56.1.39:2375
