apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: nectar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      namespace: nectar
      labels:
        app: dind
    spec:
      serviceAccountName: nectar
      containers:
        - name: dind
          image: docker:18.05-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapi
  namespace: nectar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapi
  template:
    metadata:
      namespace: nectar
      labels:
        app: kapi
    spec:
      serviceAccountName: nectar
      containers:
        - name: main
          image: xnectar/kapi:latest
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 5000
          env:
            - name: RUN_ENV
              value: production
            - name: K8S_AUTH_TYPE
              value: local
            - name: DOCKER_HOST
              value: tcp://dind.nectar:2375

---

kind: Service
apiVersion: v1
metadata:
  name: kapi
  namespace: nectar
spec:
  type: ClusterIP
  selector:
    app: kapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

kind: Service
apiVersion: v1
metadata:
  name: dind
  namespace: nectar
spec:
  type: ClusterIP
  selector:
    app: dind
  ports:
    - protocol: TCP
      port: 2375
      targetPort: 2375
