apiVersion: v1
kind: ServiceAccount
metadata:
  name: nectar
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nectar
subjects:
  - kind: User
    name: system:serviceaccount:default:nectar
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: runner
  name: runner
  namespace: default
spec:
  serviceAccount: nectar
  restartPolicy: Never
  containers:
    - name: main
      imagePullPolicy: Never
      image: test-run:latest
